version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
  api:
    build:
      context: ./
      dockerfile: Dockerfile1
    restart: always
